### ISSUE TITLE
Google map poly mouse* events not working

### ISSUE THREAD

**Issue by astelmashenko** [GoogleWebComponents/google-map#242] opened 2015-12-21 12:19 UTC
Hi,

Thanks for developing this polymer element. I need mouse* events enabled but I could not get them working, I noticed that _mouseEventsChanged is not called and listeners are not added. If I call _mouseEventsChanged at the end of _createPoly function, mouse events become working.

```javascript
    _createPoly: function() {
      // Build poly's path and register mutation listeners on first creation.
      ...  
      this._listeners = {};
      this._mouseEventsChanged();
    },
```

B.t.w. I've implemented google-map-circle, the same way as google-map-poly, and got the same issue there.

**Comment by ebidel** [comment] 2015-12-21 15:27
You should not need to call `_mouseEventsChanged` directly. It's an internal method. Can you provide a jsbin that repos the issue?

**Comment by astelmashenko** [comment] 2015-12-21 20:03
try this one http://jsbin.com/letani/edit?html,output and move mouse over the line,
open console and see no messages are shown.

Then try uncomment my version of google-map-poly import, comment out original and move mouse over polyline again, see messages in the console

**Comment by astelmashenko** [comment] 2015-12-22 22:19
@ebidel did you have a chance to look at jsbin added? Please let me know if I need to improve it somehow. Thanks

**Comment by ebidel** [comment] 2015-12-22 22:29
Probably won't have a chance until after the holidays.

**Comment by volodymyrrudyi** [comment] 2016-01-05 09:45
I'm having exactly the same issue. Actually, it affects almost all properties in this component. The problem is property observers have an implicit dependency on the order they are being called. Observers of almost all properties assume that **this.poly** should be already created, while it's created in the **_mapChanged** observer.

**Comment by volodymyrrudyi** [comment] 2016-01-05 09:58
Most likely the simplest way to resolve the issue is to create polygon/polyline instance on the  [ready()](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#ready-method) event with all required properties

**Comment by volodymyrrudyi** [comment] 2016-01-05 20:15
Actually, because of the way map is set on the component, we anyway need to explicitly forward all required events in the _createPoly method or click-events, mouse-events and drag-events will be ignored when map is changed.

I created a PR with the change and a test: https://github.com/GoogleWebComponents/google-map/pull/247

**Comment by volodymyrrudyi** [comment] 2016-01-18 09:26
@ebidel can you take a look on this, please? in some cases (like two-way binding driven map objects population) workarounds become too cumbersome and difficult to maintain, while this looks like an obvious bug in the component

**Comment by ebidel** [comment] 2016-01-19 22:53
I haven't had a chance to look at your PR (https://github.com/GoogleWebComponents/google-map/pull/248). Does that address this bug?

**Comment by astelmashenko** [comment] 2016-01-25 15:46
Yes, it does.

**Comment by volodymyrrudyi** [comment] 2016-01-25 15:47
yep, it's the fix for this issue

**Comment by ebidel** [comment] 2016-01-25 17:22
https://github.com/GoogleWebComponents/google-map/releases/tag/1.1.9 :)

**Closed by ebidel** 2016-01-25 17:22 UTC
