### ISSUE TITLE
Google-Map-Marker update position problem

### ISSUE THREAD

**Issue by Neill83** [GoogleWebComponents/google-map#119] opened 2015-03-31 10:21 UTC
Hi,

I'm using google-map, google-map-search and google-map-marker in gwt ui-binder (with xml and java class). Isn't there a possibility to update the position (long and lat) of a marker? I'm using google-map-search with google-map to find cities or whatever on the map (and it works fine) but I can't update the position of the marker. Any idea?

Thanks

**Comment by eximius313** [comment] 2015-04-14 19:32
the function designed for this purpose is map.resize()
It works, when you change the marker list, unfortunately it doesn't work, when you have a marker and you are changing its latitude and longitude - which I consider as a bug.
The workaround I have found (using Polymer) is as follows:
```javascript
<google-map id="myMap" map="{{map}}" disableDefaultUI="true" latitude="51.1270779" longitude="16.991864" fittomarkers>
			<template  repeat="{{x in workaround}}">
	          	<google-map-marker latitude="{{lat}}" longitude="{{lng}}" draggable="true" title="{{markerTitle}}"></google-map-marker>
		</template>
	</google-map>
<script>
...
searchResults: function(e){
   this.workaround = [{}];
   this.$.myMap.resize();
}
</script>
```

**Comment by ebidel** [comment] 2015-06-10 03:14
Closing as this is pre Polymer 1.0. Please reopen if you can still reproduce with the new element.

**Comment by eximius313** [comment] 2015-06-11 23:48
now is even worse, because you can not change the marker position at all!
If you do this - the map goes gray.

**Comment by atotic** [comment] 2015-06-17 06:39
do you have code that demonstrates this? We've just released 1.0.2 that fixed a bunch of blank pages.

**Comment by eximius313** [comment] 2015-06-20 10:44
I confirm, that having this code:
```
<google-map id="myMap" map="{{map}}" disable-default-ui="false" latitude="{{lat}}" longitude="{{lng}}" zoom="5" fit-to-markers>
	<google-map-marker latitude="{{lat}}" longitude="{{lng}}" draggable="true" title="T"></google-map-marker>
</google-map>
```
With the newest version of google-map component moves the marker, when ```lat``` and ```lng``` properties are chenged and ```this.$.myMap.resize()``` is called.
Unfortunately this doesn't work in the opposite side.
If you move the marker on the map, then ```latitude``` and ```longitude``` changes here:
```
<google-map-marker latitude="{{lat}}" longitude="{{lng}}" draggable="true" title="T"></google-map-marker>
```
BUT ```latitude``` and ```longitude``` DOESN'T change here (although it is the same property!)
```
<google-map id="myMap" map="{{map}}" disable-default-ui="false" latitude="{{lat}}" longitude="{{lng}}" zoom="5" fit-to-markers>
```

**Comment by eximius313** [comment] 2015-06-20 11:04
I've check that setting ```notify: true``` instead of ```reflectToAttribute: true``` on these two properties could solve the problem

**Comment by atotic** [comment] 2015-06-20 14:38
Got it: 
google-map-marker lat/long need notify attributes.

**Comment by samuelli** [comment] 2016-03-30 00:02
So this is already fixed?

**Comment by ebidel** [comment] 2016-03-30 17:35
Should be.

**Closed by ebidel** 2016-03-30 17:35 UTC
